# Generated by Django 3.1.5 on 2021-06-16 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210616_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(auto_created=True, unique=True),
        ),
    ]
